[tools]
bat = "latest"
bun = "latest"
delta = "latest"
go = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
"npm:opencode-ai" = "latest"
"pipx:ansible-core" = "latest"
"pipx:ast-grep-cli" = "latest"
"pipx:httpie" = "latest"
"pipx:meson" = "latest"
"pipx:ninja" = "latest"
ripgrep = "latest"
rust = "latest"
sheldon = "latest"
shfmt = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[settings.go]
set_gobin = false

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true
compile = false
